---
# override this:
image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-20220621.1.x86_64.qcow2
cloud_image_name: CentOS-Stream-GenericCloud-9-20220621.1.x86_64.qcow2
image_path: /home/stack
ssh_key_path: /home/stack/.ssh/id_rsa.pub
user_home: /home/stack

libvirt_files:
  - external.xml
  - management.xml
  - standalone-net.xml
