---
# Path where the config files should be pulled
# Name of the directory where the artifacts will be copy:
# TripleO podman:
tripleo_collect_dir: collect_tripleo_configs
# OCP:
crc_collect_dir: collect_ocp_configs
# Temporary remote directory where the artifacts will be copy before being synchronized on the local file system.
# For example, the TripleO standalone podman config files will be stored under /tmp on the standalone host, then
# the /tmp/collect_tripleo_configs will be copy on the local file system: /tmp/collect_tripleo_configs
# If non Linux-Unix operating system, you will have to tweak those values according to your local system.
working_dir: /tmp
# Local destination where the artifacts will be copy in order to be compare later.
local_working_dir: /tmp

# Enable/Disable config collect
collect_podman: false
collect_ocp: false

# OCP auth config
# Change those values with your personal credentials.
oc_host: https://api.crc.testing:6443
oc_user: kubeadmin
oc_passwd: 12345678
oc_bin: oc

# Move this to true if you want to log to OCP with login/password
# Keep this to false if you are already logged in or you want to do it on our own.
oc_login: false

# If you are not using a crc environment set this to false.
crc: true

# Set true if you want to pull specific files in podman container.
# Example:
# you want to pull only: /etc/keystone/keystone.conf
# instead of the whole directory: /etc/keystone/
pull_items: false
