---
- name: Collect podman
  include_tasks: collect_podman.yml
  vars:
    service: "{{ item }}"
  when: collect_podman
  with_dict: "{{ services }}"

- name: OC login
  include_tasks: ocp_login.yml
  when:
    - collect_ocp
    - oc_login

- name: Collect ocp
  include_tasks: collect_ocp.yml
  vars:
    service: "{{ item }}"
  when: collect_ocp
  with_dict: "{{ services }}"

- name: Fetch TripleO configs
  synchronize:
    src: "{{ working_dir }}/{{ tripleo_collect_dir }}"
    dest: "{{ local_working_dir }}"
    mode: pull
    use_ssh_args: yes
  when: collect_podman

- name: Fetch CRC configs
  synchronize:
    src: "{{ working_dir }}/{{ crc_collect_dir }}"
    dest: "{{ local_working_dir }}"
    mode: pull
    use_ssh_args: yes
  when: collect_ocp

- name: Cleanup TripleO
  file:
    path: "{{ working_dir }}/{{ tripleo_collect_dir }}"
    state: absent
  when:
    - collect_podman

- name: Cleanup OCP
  file:
    path: "{{ working_dir }}/{{ crc_collect_dir }}"
    state: absent
  when:
    - collect_ocp
    - ansible_connection != "local"
